### ISSUE TITLE
Looking for Seurat object

### ISSUE THREAD

**Issue by ZheFrench** [panchyni/Time_and_Dose#1]
Dear Dr. Panchy,

Your publication entitled Comparative single-cell transcriptomes of dose and time dependent epithelial–mesenchymal spectrums is a very nice study.

I'm wondering if it would be possible to share the Seurat object to retrieve the raw matrix count from the dose dependent epithelial–mesenchymal. I am also very interested in the time dependent epithelial–mesenchymal initialy from Deshmukh et al.

Deshmukh et al only gave acess to the raw sequence files and their mapping was done on an old version of the genome. This is why I'm asking to you as you did it for you study with a more recent genome version.

Thank you.

**Comment by panchyni** [comment]
Hello,

Thanks for reaching out and I appreciate your comments on our study.

The Seurat object I used for this study is currently archived so I don't have easy access to it, though it is possible to retrieve if absolutely necessary.

However, if you are mainly interested in the counts I would actually recommend working from the raw data provided in our study and Deshmukh et al. While doing this study I ran into similar challenges with older genome versions as well as older versions of Seurat and ultimately the best solution was to to work from the raw data with the newest versions of everything (genome, CellRanger, Seurat). Otherwise there is a risk at getting locked into a older version of the analysis software (both Seurant and CellRanger have gone through major version updates since our study) and this can be a particular problem with anything written in R as R generally expect users to be updating to the newest versions regularly (and downgrading to import older Seurat objects proved particularly challenging for me during 3/4 transition).

As such, I recommend you take a look at this tutorial for generating counts in CellRanger (https://www.10xgenomics.com/support/software/cell-ranger/latest/tutorials/cr-tutorial-ct). Their website can be challenging to navigate but the tutorials are pretty good and once you have all the raw counts processed the same way you can do anything you want with it.

Nick

**Comment by ZheFrench** [comment]
Thanks for you answer. 
I finally only use the dose dependent EMT from GEO.
I will think about the time dependent EMT from Deshmukh et al.  but I didn't want to pass to much time on these analysis.
Nevermind, Thank you again !

**Comment by panchyni** [comment]
Quick Addendum:

The raw reads for the dose dependent EMT can be found here: https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=882405 (Its a little hidden on the GEO site).

Might be useful if you do end up want to process the time dependent and dose dependent data together with a more modern genome/CellRanger
